export const authAppearance = {
  layout: {
    logoPlacement: 'none' as const,
    socialButtonsPlacement: 'top' as const,
    socialButtonsVariant: 'blockButton' as const,
  },
  variables: {
    colorPrimary: 'var(--foreground)',
    colorBackground: 'var(--background)',
    colorText: 'var(--foreground)',
    colorTextSecondary: 'var(--muted-foreground)',
    colorInputBackground: 'var(--background)',
    colorInputText: 'var(--foreground)',
    colorNeutral: 'var(--foreground)',
    colorDanger: 'var(--destructive)',
    borderRadius: '0.625rem',
    fontFamily: 'var(--font-sans), Inter, sans-serif',
    fontSize: '14px',
    spacingUnit: '17px',
  },
  elements: {
    rootBox: 'w-full max-w-full',
    card: 'w-full max-w-full gap-0 bg-transparent p-0 shadow-none',
    cardBox: 'w-full max-w-full sm:max-w-[410px] border-0 bg-transparent shadow-none',
    header: 'hidden',
    headerTitle: 'hidden',
    headerSubtitle: 'hidden',
    socialButtonsBlockButton:
      'h-10 rounded-[0.625rem] border border-border bg-card text-sm font-medium text-foreground shadow-none transition-colors hover:bg-muted/60 dark:bg-card dark:text-foreground dark:hover:bg-muted/60',
    socialButtonsBlockButtonText: 'font-medium text-foreground',
    socialButtonsProviderIcon: 'text-foreground',
    dividerLine: 'bg-border',
    dividerText: 'bg-background px-2 text-xs text-muted-foreground',
    formField: 'space-y-1.5',
    formFieldLabel: 'mb-1 text-sm font-medium text-foreground',
    formFieldInput:
      'h-10 rounded-[0.625rem] border border-input bg-background px-3 text-sm text-foreground shadow-none outline-none transition-colors placeholder:text-muted-foreground focus:border-ring focus:ring-2 focus:ring-ring/25 dark:bg-background dark:text-foreground dark:placeholder:text-muted-foreground',
    formFieldInputShowPasswordButton: 'text-muted-foreground transition-colors hover:text-foreground',
    formButtonPrimary:
      'h-10 w-full rounded-[0.625rem] bg-foreground text-sm font-medium text-background shadow-none transition-colors hover:bg-foreground/90 focus:ring-2 focus:ring-ring/30',
    footer: 'hidden',
    footerActionLink: 'font-medium text-foreground underline-offset-4 hover:underline',
    footerActionText: 'text-sm text-muted-foreground',
    identityPreview: 'rounded-[0.625rem] border border-border bg-card text-foreground shadow-none',
    identityPreviewText: 'text-sm text-foreground',
    identityPreviewEditButton: 'text-muted-foreground transition-colors hover:text-foreground',
    formResendCodeLink: 'text-sm font-medium text-foreground underline-offset-4 hover:underline',
    otpCodeFieldInput:
      'rounded-[0.625rem] border border-input bg-background text-lg font-semibold text-foreground shadow-none focus:border-ring focus:ring-2 focus:ring-ring/25',
    formFieldErrorText: 'mt-1 text-xs text-destructive',
    alert: 'rounded-[0.625rem] border border-border bg-card text-foreground',
    alertText: 'text-sm text-foreground',
    formFieldWarningText: 'text-xs text-destructive',
  },
}
