export type Comparison = {
  slug: string
  competitor: string
  competitorUrl: string
  title: string
  description: string
  date: string
  comparisonRows: { feature: string; kamforms: string; them: string }[]
  advantages: string[]
  disadvantage: string
  conclusion: string
  faqs: { q: string; r: string }[]
}

export const COMPARISONS: Comparison[] = [
  {
    slug: 'kamforms-vs-typeform',
    competitor: 'Typeform',
    competitorUrl: 'https://typeform.com',
    title: 'Kamforms vs Typeform : le comparatif 2026 pour l\'Afrique',
    description: 'Comparez Kamforms et Typeform pour la création de formulaires WhatsApp en Afrique. Prix, notifications WhatsApp, paiements Mobile Money (à venir), génération IA.',
    date: '2026-07-20',
    comparisonRows: [
      { feature: 'Prix mensuel', kamforms: 'Gratuit, puis 3 500 FCFA (6$)', them: 'À partir de 29$/mois' },
      { feature: 'Notifications WhatsApp', kamforms: 'Oui, en moins de 5 secondes', them: 'Email uniquement' },
      { feature: 'Paiements Mobile Money', kamforms: 'À venir (Orange Money, MTN, Wave)', them: 'Non (Stripe/PayPal uniquement)' },
      { feature: 'Génération IA', kamforms: 'Oui, en français', them: 'Oui, en anglais uniquement' },
      { feature: 'Import Google Forms', kamforms: 'Oui, en 1 clic', them: 'Non' },
      { feature: 'Self-hosting', kamforms: 'Oui', them: 'Non' },
      { feature: 'Multi-étapes', kamforms: 'Oui', them: 'Oui' },
      { feature: 'Prix en FCFA', kamforms: 'Oui', them: 'Non' },
      { feature: 'Optimisé 3G/4G', kamforms: 'Oui', them: 'Non' },
    ],
    advantages: [
      'Kamforms est jusqu\'à 5x moins cher que Typeform',
      'Notifications WhatsApp vs email : 5 secondes vs 90 minutes',
      'Mobile Money (Orange Money, MTN, Wave) vs Stripe/PayPal non disponibles en Afrique',
      'IA en français vs anglais uniquement',
      'Import Google Forms en 1 clic',
      'Self-hosting pour contrôle des données',
    ],
    disadvantage: 'Typeform a une bibliothèque de templates plus large et une reconnaissance de marque mondiale plus établie. Son design conversationnel est une référence.',
    conclusion: 'Pour les PME africaines qui utilisent WhatsApp et le Mobile Money (à venir), Kamforms est objectivement plus adapté et moins cher que Typeform.',
    faqs: [
      { q: 'Quel est le moins cher entre Kamforms et Typeform ?', r: 'Kamforms est gratuit pour commencer puis Pro à 3 500 FCFA/mois (6$/mois). Typeform commence à 29$/mois. Kamforms est jusqu\'à 5x moins cher.' },
      { q: 'Est-ce que Typeform supporte les paiements Mobile Money ?', r: 'Non. Typeform s\'intègre avec Stripe et PayPal uniquement. Kamforms supportera Orange Money, MTN Mobile Money et Wave (à venir).' },
      { q: 'Puis-je importer mes formulaires Typeform dans Kamforms ?', r: 'Pas directement, mais vous pouvez importer vos formulaires Google Forms. Kamforms permet aussi la génération par IA en décrivant votre besoin.' },
    ],
  },
  {
    slug: 'kamforms-vs-jotform',
    competitor: 'Jotform',
    competitorUrl: 'https://jotform.com',
    title: 'Kamforms vs Jotform : le comparatif 2026 pour l\'Afrique',
    description: 'Comparez Kamforms et Jotform pour les formulaires WhatsApp en Afrique. Prix, fonctionnalités, notifications, Mobile Money (à venir).',
    date: '2026-07-20',
    comparisonRows: [
      { feature: 'Prix mensuel', kamforms: 'Gratuit, puis 3 500 FCFA (6$)', them: 'À partir de 34$/mois (Bronze)' },
      { feature: 'Notifications WhatsApp', kamforms: 'Oui, en moins de 5 secondes', them: 'Email uniquement (intégration Zapier payante)' },
      { feature: 'Paiements Mobile Money', kamforms: 'À venir (Orange Money, MTN, Wave)', them: 'Non (PayPal/Stripe uniquement)' },
      { feature: 'Génération IA', kamforms: 'Oui, en français', them: 'Oui (IA Jotform)' },
      { feature: 'Import Google Forms', kamforms: 'Oui, en 1 clic', them: 'Non' },
      { feature: 'Self-hosting', kamforms: 'Oui', them: 'Non' },
      { feature: 'Nombre de formulaires', kamforms: '10 (Pro)', them: '25 (Bronze)' },
      { feature: 'Prix en FCFA', kamforms: 'Oui', them: 'Non' },
      { feature: 'Optimisé mobile Afrique', kamforms: 'Oui (3G/4G)', them: 'Non' },
    ],
    advantages: [
      'Kamforms est 5x moins cher que Jotform',
      'Notifications WhatsApp natives vs email + Zapier payant',
      'Mobile Money (à venir) vs pas de support africain',
      'IA en français + import Google Forms',
      'Self-hosting disponible',
    ],
    disadvantage: 'Jotform propose plus de templates (10 000+) et des intégrations plus nombreuses via Zapier. Son éditeur par glisser-déposer est plus complet.',
    conclusion: 'Jotform est un outil puissant pour les marchés occidentaux. Kamforms est plus adapté, moins cher et plus pertinent pour les PME africaines.',
    faqs: [
      { q: 'Kamforms ou Jotform : lequel est le moins cher ?', r: 'Kamforms est gratuit, puis Pro à 3 500 FCFA/mois (6$/mois). Jotform Bronze est à 34$/mois. Kamforms est 5x moins cher.' },
      { q: 'Jotform supporte-t-il les paiements Orange Money ?', r: 'Non. Jotform supporte PayPal, Stripe et Square. Kamforms supportera Orange Money, MTN Mobile Money et Wave (à venir).' },
    ],
  },
  {
    slug: 'kamforms-vs-tally',
    competitor: 'Tally',
    competitorUrl: 'https://tally.so',
    title: 'Kamforms vs Tally : le comparatif 2026',
    description: 'Comparez Kamforms et Tally.so pour les formulaires WhatsApp. Prix, fonctionnalités, notifications, Mobile Money (à venir) pour l\'Afrique.',
    date: '2026-07-20',
    comparisonRows: [
      { feature: 'Prix mensuel', kamforms: 'Gratuit, puis 3 500 FCFA (6$)', them: 'Gratuit, puis 29$/mois (Pro)' },
      { feature: 'Notifications WhatsApp', kamforms: 'Oui, en moins de 5 secondes', them: 'Non (email uniquement)' },
      { feature: 'Paiements Mobile Money', kamforms: 'À venir (Orange Money, MTN, Wave)', them: 'Non (Stripe uniquement)' },
      { feature: 'Génération IA', kamforms: 'Oui, en français', them: 'Non' },
      { feature: 'Import Google Forms', kamforms: 'Oui, en 1 clic', them: 'Non' },
      { feature: 'Self-hosting', kamforms: 'Oui', them: 'Non' },
      { feature: 'Nombre de réponses', kamforms: '1 000/mois (Pro)', them: 'Illimitées (Pro)' },
      { feature: 'Limite de réponses', kamforms: 'Configurable', them: 'Non' },
      { feature: 'Paiements en FCFA', kamforms: 'Oui', them: 'Non' },
    ],
    advantages: [
      'Notifications WhatsApp natives vs aucune',
      'Mobile Money (à venir) vs Stripe uniquement',
      'Génération IA en français',
      'Import Google Forms',
      'Self-hosting disponible',
      'Prix en FCFA',
    ],
    disadvantage: 'Tally est très simple d\'utilisation et son interface minimaliste est appréciée. Le plan gratuit de Tally est généreux (nombre illimité de réponses).',
    conclusion: 'Tally est un excellent outil gratuit pour des formulaires simples. Kamforms apporte les fonctionnalités WhatsApp et Mobile Money (à venir) qui manquent aux PME africaines.',
    faqs: [
      { q: 'Tally est-il gratuit ?', r: 'Oui, Tally a un plan gratuit généreux. Mais le plan Pro est à 29$/mois, contre 6$/mois pour Kamforms Pro.' },
      { q: 'Est-ce que Tally a des notifications WhatsApp ?', r: 'Non. Tally n\'envoie que des notifications par email. Kamforms envoie chaque réponse sur WhatsApp en moins de 5 secondes.' },
    ],
  },
  {
    slug: 'kamforms-vs-fillout',
    competitor: 'Fillout',
    competitorUrl: 'https://fillout.com',
    title: 'Kamforms vs Fillout : le comparatif 2026',
    description: 'Comparez Kamforms et Fillout pour les formulaires WhatsApp en Afrique. Prix, fonctionnalités, Mobile Money (à venir), notifications.',
    date: '2026-07-20',
    comparisonRows: [
      { feature: 'Prix mensuel', kamforms: 'Gratuit, puis 3 500 FCFA (6$)', them: 'Gratuit, puis 24$/mois (Pro)' },
      { feature: 'Notifications WhatsApp', kamforms: 'Oui, en moins de 5 secondes', them: 'Email + Slack' },
      { feature: 'Paiements Mobile Money', kamforms: 'À venir (Orange Money, MTN, Wave)', them: 'Non (Stripe)' },
      { feature: 'Génération IA', kamforms: 'Oui, en français', them: 'Oui (IA)' },
      { feature: 'Import Google Forms', kamforms: 'Oui, en 1 clic', them: 'Oui' },
      { feature: 'Self-hosting', kamforms: 'Oui', them: 'Non' },
      { feature: 'Base de données', kamforms: 'Dashboard + export CSV', them: 'Base de données intégrée' },
      { feature: 'Prix en FCFA', kamforms: 'Oui', them: 'Non' },
    ],
    advantages: [
      'Notifications WhatsApp natives',
      'Mobile Money (à venir : Orange Money, MTN, Wave)',
      'IA en français',
      '4x moins cher que Fillout Pro',
      'Self-hosting disponible',
    ],
    disadvantage: 'Fillout a une base de données intégrée plus poussée et des templates modernes. Son éditeur est très fluide.',
    conclusion: 'Fillout est un bon outil moderne. Kamforms est mieux adapté au marché africain avec WhatsApp, Mobile Money (à venir) et le prix en FCFA.',
    faqs: [
      { q: 'Fillout a-t-il des notifications WhatsApp ?', r: 'Non. Fillout supporte les notifications par email et Slack. Kamforms envoie les notifications directement sur WhatsApp.' },
      { q: 'Quel est le moins cher entre Fillout et Kamforms ?', r: 'Kamforms Pro est à 6$/mois (3 500 FCFA). Fillout Pro est à 24$/mois. Kamforms est 4x moins cher.' },
    ],
  },
  {
    slug: 'kamforms-vs-wati',
    competitor: 'WATI',
    competitorUrl: 'https://wati.io',
    title: 'Kamforms vs WATI : le comparatif 2026 pour l\'Afrique',
    description: 'Comparez Kamforms et WATI pour les formulaires WhatsApp et l\'automatisation. Prix, fonctionnalités, Mobile Money (à venir), utilisation PME.',
    date: '2026-07-20',
    comparisonRows: [
      { feature: 'Prix mensuel', kamforms: 'Gratuit, puis 3 500 FCFA (6$)', them: 'À partir de 49$/mois' },
      { feature: 'Création de formulaires', kamforms: 'Native avec IA', them: 'Via chatbot, pas de formulaire natif' },
      { feature: 'Paiements Mobile Money', kamforms: 'À venir (Orange Money, MTN, Wave)', them: 'Non' },
      { feature: 'Génération IA', kamforms: 'Oui, en français', them: 'Non' },
      { feature: 'Import Google Forms', kamforms: 'Oui, en 1 clic', them: 'Non' },
      { feature: 'Self-hosting', kamforms: 'Oui', them: 'Non' },
      { feature: 'Chatbot WhatsApp', kamforms: 'Non', them: 'Oui (conversationnel)' },
      { feature: 'CRM intégré', kamforms: 'Non (export CSV)', them: 'Oui' },
      { feature: 'Prix en FCFA', kamforms: 'Oui', them: 'Non' },
    ],
    advantages: [
      'Kamforms est 8x moins cher que WATI',
      'Vrai formulaire vs chatbot conversationnel',
      'Mobile Money (à venir) vs pas de paiement intégré',
      'IA en français + import Google Forms',
      'Self-hosting disponible',
    ],
    disadvantage: 'WATI est une plateforme WhatsApp Business API complète avec chatbot, CRM et automation. Kamforms se concentre sur les formulaires uniquement.',
    conclusion: 'WATI est une solution WhatsApp API professionnelle pour grands volumes. Kamforms est plus simple, moins cher et plus adapté aux PME pour la collecte de données.',
    faqs: [
      { q: 'WATI ou Kamforms : quel est le meilleur pour une PME ?', r: 'Si vous avez besoin uniquement de collecter des données (devis, inscriptions, commandes), Kamforms est plus simple et 8x moins cher. Si vous avez besoin d\'un chatbot WhatsApp complet, WATI est plus adapté.' },
      { q: 'Est-ce que WATI supporte les paiements Orange Money ?', r: 'Non. WATI ne propose pas d\'intégration de paiement native. Kamforms intégrera Orange Money, MTN et Wave (à venir).' },
    ],
  },
  {
    slug: 'kamforms-vs-respond-io',
    competitor: 'Respond.io',
    competitorUrl: 'https://respond.io',
    title: 'Kamforms vs Respond.io : le comparatif 2026',
    description: 'Comparez Kamforms et Respond.io pour la collecte de données WhatsApp en Afrique. Prix, fonctionnalités, Mobile Money (à venir).',
    date: '2026-07-20',
    comparisonRows: [
      { feature: 'Prix mensuel', kamforms: 'Gratuit, puis 3 500 FCFA (6$)', them: 'À partir de 67$/mois (Pro)' },
      { feature: 'Création de formulaires', kamforms: 'Native avec IA', them: 'Via message, pas de formulaire natif' },
      { feature: 'Paiements Mobile Money', kamforms: 'À venir (Orange Money, MTN, Wave)', them: 'Non' },
      { feature: 'Génération IA', kamforms: 'Oui, en français', them: 'Non' },
      { feature: 'Import Google Forms', kamforms: 'Oui, en 1 clic', them: 'Non' },
      { feature: 'Self-hosting', kamforms: 'Oui', them: 'Non' },
      { feature: 'Multi-canal', kamforms: 'WhatsApp uniquement', them: 'WhatsApp, Messenger, Telegram, etc.' },
      { feature: 'Prix en FCFA', kamforms: 'Oui', them: 'Non' },
    ],
    advantages: [
      'Kamforms est 11x moins cher que Respond.io',
      'Formulaire structuré vs message non structuré',
      'Mobile Money (à venir)',
      'IA en français',
      'Self-hosting disponible',
    ],
    disadvantage: 'Respond.io est une plateforme omnicanale (WhatsApp, Messenger, Telegram, Instagram) avec CRM intégré. Kamforms est spécialisé formulaires WhatsApp uniquement.',
    conclusion: 'Respond.io est une solution enterprise pour la gestion omnicanale. Kamforms est plus spécifique, plus simple et beaucoup moins cher pour la collecte de données WhatsApp.',
    faqs: [
      { q: 'Respond.io est-il moins cher que Kamforms ?', r: 'Non. Respond.io commence à 67$/mois, contre 6$/mois pour Kamforms Pro. Kamforms est 11x moins cher.' },
      { q: 'Puis-je créer des formulaires avec Respond.io ?', r: 'Respond.io permet d\'envoyer des messages, mais pas de créer des formulaires structurés avec validation, logique conditionnelle et paiement (à venir) comme Kamforms.' },
    ],
  },
  {
    slug: 'kamforms-vs-google-forms',
    competitor: 'Google Forms',
    competitorUrl: 'https://forms.google.com',
    title: 'Kamforms vs Google Forms : le comparatif 2026',
    description: 'Comparez Kamforms et Google Forms pour les PME africaines. Notifications WhatsApp, Mobile Money (à venir), génération IA, import en 1 clic.',
    date: '2026-07-20',
    comparisonRows: [
      { feature: 'Prix', kamforms: 'Gratuit, puis 3 500 FCFA (6$)', them: 'Gratuit' },
      { feature: 'Notifications WhatsApp', kamforms: 'Oui, en moins de 5 secondes', them: 'Email uniquement (90 min)' },
      { feature: 'Paiements Mobile Money', kamforms: 'À venir (Orange Money, MTN, Wave)', them: 'Non' },
      { feature: 'Génération IA', kamforms: 'Oui, en français', them: 'Non' },
      { feature: 'Compte requis pour répondre', kamforms: 'Non', them: 'Oui (compte Google)' },
      { feature: 'Self-hosting', kamforms: 'Oui', them: 'Non' },
      { feature: 'Multi-étapes', kamforms: 'Oui', them: 'Non' },
      { feature: 'Logique conditionnelle', kamforms: 'Oui', them: 'Limitée' },
    ],
    advantages: [
      'Notifications WhatsApp vs email : 5 secondes vs 90 minutes',
      'Mobile Money (à venir : Orange Money, MTN, Wave)',
      'Pas de compte requis pour vos clients',
      'IA en français + import Google Forms en 1 clic',
      'Self-hosting pour contrôle des données',
    ],
    disadvantage: 'Google Forms est gratuit et intégré à Google Drive. Pour des formulaires simples sans besoin de notifications WhatsApp ni Mobile Money, il reste une option valable.',
    conclusion: 'Google Forms fait le job pour des formulaires simples. Kamforms apporte les fonctionnalités qui manquent aux PME africaines : WhatsApp, Mobile Money (à venir), IA et pas de compte Google requis.',
    faqs: [
      { q: 'Puis-je importer mes formulaires Google Forms dans Kamforms ?', r: 'Oui, Kamforms permet d\'importer vos formulaires Google Forms en 1 clic. Questions, options et logique sont transférées.' },
      { q: 'Google Forms est-il gratuit ?', r: 'Oui, Google Forms est gratuit. Mais il n\'a pas de notifications WhatsApp, pas de Mobile Money, pas d\'IA, et nécessite un compte Google pour répondre.' },
    ],
  },
  {
    slug: 'kamforms-vs-manychat',
    competitor: 'ManyChat',
    competitorUrl: 'https://manychat.com',
    title: 'Kamforms vs ManyChat : formulaire ou chatbot WhatsApp ?',
    description: 'Comparez Kamforms et ManyChat pour la collecte de données WhatsApp. Différence entre formulaire structuré et chatbot conversationnel.',
    date: '2026-07-20',
    comparisonRows: [
      { feature: 'Prix mensuel', kamforms: 'Gratuit, puis 3 500 FCFA (6$)', them: 'Gratuit, puis à partir de 15$/mois' },
      { feature: 'Type d\'outil', kamforms: 'Formulaire structuré', them: 'Chatbot conversationnel' },
      { feature: 'Collecte de données', kamforms: 'Données structurées automatiquement', them: 'Messages non structurés' },
      { feature: 'Paiements Mobile Money', kamforms: 'À venir (Orange Money, MTN, Wave)', them: 'Non' },
      { feature: 'Génération IA', kamforms: 'Oui, en français', them: 'Oui' },
      { feature: 'Import Google Forms', kamforms: 'Oui, en 1 clic', them: 'Non' },
      { feature: 'Self-hosting', kamforms: 'Oui', them: 'Non' },
      { feature: 'Automatisation', kamforms: 'Notifications + paliers', them: 'Flux conversationnel complet' },
    ],
    advantages: [
      'Données structurées vs messages non structurés',
      'Mobile Money (à venir)',
      'Pas de configuration de chatbot complexe',
      'IA en français + import Google Forms',
      'Self-hosting',
    ],
    disadvantage: 'ManyChat permet des automatisations conversationnelles avancées (sequences, tagging, CRM). Kamforms est spécialisé dans les formulaires uniquement.',
    conclusion: 'ManyChat est un chatbot marketing. Kamforms est un outil de formulaire. Pour collecter des données structurées (devis, inscriptions, commandes), Kamforms est plus efficace et moins cher.',
    faqs: [
      { q: 'Kamforms ou ManyChat pour collecter des commandes ?', r: 'Kamforms. Les commandes via formulaire sont structurées (nom, produit, quantité, adresse). ManyChat envoie des messages libres que vous devez traiter manuellement.' },
      { q: 'ManyChat supporte-t-il les paiements Mobile Money ?', r: 'Non. ManyChat supporte Stripe et PayPal. Kamforms supportera Orange Money, MTN et Wave (à venir).' },
    ],
  },
]
