ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "plan" TEXT NOT NULL DEFAULT 'free';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "billingStatus" TEXT NOT NULL DEFAULT 'free';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "billingPeriod" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "billingPlanId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "billingReference" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "planActivatedAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "planExpiresAt" TIMESTAMP(3);
